/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.ProductDAO;
import domain.Product;
import gui.helpers.SimpleListModel;
import java.util.Collection;
import javax.swing.JOptionPane;

/**
 *
 * @author liuzh139
 */
public class ProductReportDialog extends javax.swing.JDialog {

   private ProductDAO dao;
   private SimpleListModel productsModel;
   private SimpleListModel categoryModel;

   /**
    * Creates new form ProductReportDialog
    */
   public ProductReportDialog(java.awt.Frame parent, boolean modal, ProductDAO dao) {
      super(parent, modal);
      initComponents();

      this.dao = dao;

      productsModel = new SimpleListModel(dao.getAll());
      categoryModel = new SimpleListModel(dao.getCategory());

      lstProducts.setModel(productsModel);
      cmbCategory.setModel(categoryModel);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      btnEdit = new javax.swing.JButton();
      btnDelete = new javax.swing.JButton();
      btnClose = new javax.swing.JButton();
      btnSearch = new javax.swing.JButton();
      cmbCategory = new javax.swing.JComboBox();
      txtId = new javax.swing.JTextField();
      jScrollPane1 = new javax.swing.JScrollPane();
      lstProducts = new javax.swing.JList();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

      jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      jLabel1.setText("View Products");
      jLabel1.setName("jLabel1"); // NOI18N

      jLabel2.setText("Search by ID:");
      jLabel2.setName("jLabel2"); // NOI18N

      jLabel3.setText("Category Filter:");
      jLabel3.setName("jLabel3"); // NOI18N

      btnEdit.setText("Edit");
      btnEdit.setName("btnEdit"); // NOI18N
      btnEdit.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnEditActionPerformed(evt);
         }
      });

      btnDelete.setText("Delete");
      btnDelete.setName("btnDelete"); // NOI18N
      btnDelete.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnDeleteActionPerformed(evt);
         }
      });

      btnClose.setText("Close");
      btnClose.setName("btnClose"); // NOI18N
      btnClose.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCloseActionPerformed(evt);
         }
      });

      btnSearch.setText("Search");
      btnSearch.setName("btnSearch"); // NOI18N
      btnSearch.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSearchActionPerformed(evt);
         }
      });

      cmbCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
      cmbCategory.setName("cmbCategory"); // NOI18N
      cmbCategory.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            cmbCategoryActionPerformed(evt);
         }
      });

      txtId.setName("txtSearch"); // NOI18N

      jScrollPane1.setName("jScrollPane1"); // NOI18N

      lstProducts.setModel(new javax.swing.AbstractListModel() {
         String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
         public int getSize() { return strings.length; }
         public Object getElementAt(int i) { return strings[i]; }
      });
      lstProducts.setName("lstProducts"); // NOI18N
      jScrollPane1.setViewportView(lstProducts);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addContainerGap()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSearch))
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                     .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(txtId)
                        .addGap(75, 75, 75))
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE))))
               .addGroup(layout.createSequentialGroup()
                  .addGap(149, 149, 149)
                  .addComponent(jLabel1)
                  .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel2)
               .addComponent(btnSearch)
               .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel3)
               .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnEdit)
               .addComponent(btnDelete)
               .addComponent(btnClose))
            .addContainerGap(14, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
      if (!lstProducts.isSelectionEmpty()) {
         Product product = (Product) lstProducts.getSelectedValue(); //there is no such a method in SimpleListModel.java
         int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete the product " + product.toString()); //nest the ID and Name in it?
         if (result == JOptionPane.YES_OPTION) {

            dao.delete(product);
            productsModel.updateItems(dao.getAll());
         }
         lstProducts.clearSelection();
      }
   }//GEN-LAST:event_btnDeleteActionPerformed

   private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
      this.dispose();
   }//GEN-LAST:event_btnCloseActionPerformed

   private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
      if (!lstProducts.isSelectionEmpty()) {
         Product product = (Product) lstProducts.getSelectedValue();

         ProductDialog frame = new ProductDialog(this, true, product, dao);
         frame.setLocationRelativeTo(this);
         frame.setVisible(true);

         productsModel.updateItems(dao.getAll());
         lstProducts.clearSelection();
      }
   }//GEN-LAST:event_btnEditActionPerformed

   private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
      Integer productId = Integer.parseInt(txtId.getText());
      Product product = dao.getById(productId);

      productsModel.updateItems(product);
   }//GEN-LAST:event_btnSearchActionPerformed

   private void cmbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoryActionPerformed
      Collection <Product> products;
      
      if (cmbCategory.getSelectedIndex() == -1) {
         products = dao.getAll();
      } else {
         //get the selected category
         String st = cmbCategory.getSelectedItem().toString();
         products = dao.getByCategory(st);
      }
      productsModel.updateItems(products);

   }//GEN-LAST:event_cmbCategoryActionPerformed
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnClose;
   private javax.swing.JButton btnDelete;
   private javax.swing.JButton btnEdit;
   private javax.swing.JButton btnSearch;
   private javax.swing.JComboBox cmbCategory;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JList lstProducts;
   private javax.swing.JTextField txtId;
   // End of variables declaration//GEN-END:variables
}
