/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.DAOException;
import dao.ProductDAO;
import domain.Product;
import gui.helpers.SimpleListModel;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;
import javax.validation.ConstraintViolation;
import javax.validation.Validation;
import javax.validation.Validator;
import javax.validation.ValidatorFactory;

/**
 *
 * @author liuzh139
 */
public class ProductDialog extends javax.swing.JDialog {

   private ProductDAO dao;
   private Product product;

   /**
    * Creates new form ProductDialog
    */
   public ProductDialog(java.awt.Window parent, boolean modal, ProductDAO dao) {
      super(parent);
      super.setModal(modal);
      this.dao = dao;
      this.product = new Product();

      initComponents();
      cmbCategory.setEditable(true);
      SimpleListModel getCategory = new SimpleListModel(dao.getCategory());
      cmbCategory.setModel(getCategory);

      // define the input format
      DecimalFormat integerFormat = new DecimalFormat("#0");
      // create a formatter
      NumberFormatter integerFormatter = new NumberFormatter(integerFormat);
      // define the type that the formatter will return
      integerFormatter.setValueClass(Integer.class);
      // don’t allow the user to enter values that don’t match the required format
      integerFormatter.setAllowsInvalid(false);
      // create a factory for the formatter
      DefaultFormatterFactory factory = new DefaultFormatterFactory(integerFormatter);

      // install the factory in the text field
      txtId.setFormatterFactory(factory);
      txtStock.setFormatterFactory(factory);


      // define the input format
      DecimalFormat doubleFormat = new DecimalFormat("#0.00");
      // create a formatter
      NumberFormatter doubleFormatter = new NumberFormatter(doubleFormat);
      // define the type that the formatter will return
      doubleFormatter.setValueClass(Double.class);
      // don’t allow the user to enter values that don’t match the required format
      doubleFormatter.setAllowsInvalid(false);
      // create a factory for the formatter
      DefaultFormatterFactory facDouble = new DefaultFormatterFactory(doubleFormatter);

      // install the facDouble in the text field
      txtPrice.setFormatterFactory(facDouble);

   }

   /**
    *
    * @param parent
    * @param modal
    * @param product
    */
   public ProductDialog(java.awt.Window parent, boolean modal, Product product, ProductDAO dao) {
      this(parent, modal, dao);
      this.product = product;

      txtId.setValue(product.getId());
      txtId.setEditable(false); //set the ID uneditable  
      txtName.setText(product.getName());
      cmbCategory.setSelectedItem(product.getCategory());
      txtDescription.setText(product.getDescription());
      txtPrice.setValue(product.getPrice());
      txtStock.setValue(product.getStock());
   }

   public ProductDialog() {
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      lblId = new javax.swing.JLabel();
      lblName = new javax.swing.JLabel();
      lblDescription = new javax.swing.JLabel();
      lblCategory = new javax.swing.JLabel();
      lblPrice = new javax.swing.JLabel();
      lblStock = new javax.swing.JLabel();
      txtName = new javax.swing.JTextField();
      btnSave = new javax.swing.JButton();
      btnCancel = new javax.swing.JButton();
      cmbCategory = new javax.swing.JComboBox();
      jScrollPane1 = new javax.swing.JScrollPane();
      txtDescription = new javax.swing.JTextArea();
      txtId = new javax.swing.JFormattedTextField();
      txtPrice = new javax.swing.JFormattedTextField();
      txtStock = new javax.swing.JFormattedTextField();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

      jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
      jLabel1.setText("Product Editor");
      jLabel1.setName("jLabel1"); // NOI18N

      lblId.setText("ID:");
      lblId.setName("lblId"); // NOI18N

      lblName.setText("Name:");
      lblName.setName("lblName"); // NOI18N

      lblDescription.setText("Description:");
      lblDescription.setName("lblDescription"); // NOI18N

      lblCategory.setText("Category:");
      lblCategory.setName("lblCategory"); // NOI18N

      lblPrice.setText("Price:");
      lblPrice.setName("lblPrice"); // NOI18N

      lblStock.setText("Quantity in Stock:");
      lblStock.setName("lblStock"); // NOI18N

      txtName.setName("txtName"); // NOI18N

      btnSave.setText("Save");
      btnSave.setName("btnSave"); // NOI18N
      btnSave.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSaveActionPerformed(evt);
         }
      });

      btnCancel.setText("Cancel");
      btnCancel.setName("btnCancel"); // NOI18N
      btnCancel.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCancelActionPerformed(evt);
         }
      });

      cmbCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
      cmbCategory.setName("cmbCategory"); // NOI18N
      cmbCategory.addComponentListener(new java.awt.event.ComponentAdapter() {
         public void componentMoved(java.awt.event.ComponentEvent evt) {
            cmbCategoryComponentMoved(evt);
         }
      });

      jScrollPane1.setName("jScrollPane1"); // NOI18N

      txtDescription.setColumns(20);
      txtDescription.setRows(5);
      txtDescription.setName("txtDescription"); // NOI18N
      jScrollPane1.setViewportView(txtDescription);

      txtId.setName("txtId"); // NOI18N
      txtId.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtIdActionPerformed(evt);
         }
      });

      txtPrice.setName("txtPrice"); // NOI18N

      txtStock.setName("txtStock"); // NOI18N

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(lblId, javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(lblDescription, javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(lblCategory, javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(lblPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(lblStock, javax.swing.GroupLayout.Alignment.TRAILING))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(cmbCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(jScrollPane1)
                     .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(txtId)
                     .addComponent(txtPrice)
                     .addComponent(txtStock)))
               .addGroup(layout.createSequentialGroup()
                  .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(162, 162, 162))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(lblId))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(lblName)
               .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(lblDescription)
                  .addGap(0, 0, Short.MAX_VALUE))
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(lblCategory)
                     .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(lblPrice)
               .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(6, 6, 6)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(lblStock)
               .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(9, 9, 9)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnSave)
               .addComponent(btnCancel))
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
      this.dispose();
   }//GEN-LAST:event_btnCancelActionPerformed

   private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
      try {
         product.setId((Integer) txtId.getValue());
         product.setName(txtName.getText());
         product.setDescription(txtDescription.getText());
         product.setCategory((String) cmbCategory.getSelectedItem());
         product.setPrice((Double) txtPrice.getValue());
         product.setStock((Integer) txtStock.getValue());

         // create the validator factory
         ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
         // get a validator from the factory
         Validator validator = factory.getValidator();
         // validate the student object
         Set<ConstraintViolation<Product>> constraintViolations = validator.validate(product);
         // check if any constraints were violated
         if (!constraintViolations.isEmpty()) {
            StringBuilder message = new StringBuilder();
            // loop through the violations extracting the message for each
            for (ConstraintViolation<Product> violation : constraintViolations) {
               message.append(violation.getMessage()).append("\n");
            }
            // show a message box to the user with all the messages
            JOptionPane.showMessageDialog(this, message.toString(),
                    "Input Problem", JOptionPane.WARNING_MESSAGE);
            // exit the save method, since the data is not valid
            return;
         }
         dao.save(product);
         this.dispose();
      } catch (DAOException ex) {
         throw new DAOException(ex.getMessage(), ex);
      }
   }//GEN-LAST:event_btnSaveActionPerformed

   private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtIdActionPerformed

   private void cmbCategoryComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_cmbCategoryComponentMoved
      // TODO add your handling code here:
   }//GEN-LAST:event_cmbCategoryComponentMoved
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnCancel;
   private javax.swing.JButton btnSave;
   private javax.swing.JComboBox cmbCategory;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JLabel lblCategory;
   private javax.swing.JLabel lblDescription;
   private javax.swing.JLabel lblId;
   private javax.swing.JLabel lblName;
   private javax.swing.JLabel lblPrice;
   private javax.swing.JLabel lblStock;
   private javax.swing.JTextArea txtDescription;
   private javax.swing.JFormattedTextField txtId;
   private javax.swing.JTextField txtName;
   private javax.swing.JFormattedTextField txtPrice;
   private javax.swing.JFormattedTextField txtStock;
   // End of variables declaration//GEN-END:variables
}
